spring:
  application:
    name: data-dictionary-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/data_dict?useUnicode=true&serverTimezone=Asia/Shanghai

logging:
  level:
    com:
      baomidou:
        mybatisplus=debug:

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true