spring:
  application:
    name: dictionary-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mall_dictionary?useUnicode=true&serverTimezone=Asia/Shanghai

server:
  port: 8003
