spring:
  application:
    name: system-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/system?useUnicode=true&serverTimezone=Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true